/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardWaterRouteImport } from './routes/dashboard/water'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as DashboardWalletRouteRouteImport } from './routes/dashboard/wallet/route'
import { Route as DashboardUtilitiesRouteRouteImport } from './routes/dashboard/utilities/route'
import { Route as DashboardSettingsRouteRouteImport } from './routes/dashboard/settings/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardWalletIndexRouteImport } from './routes/dashboard/wallet/index'
import { Route as DashboardUtilitiesIndexRouteImport } from './routes/dashboard/utilities/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardChatbotIndexRouteImport } from './routes/dashboard/chatbot/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardWalletHistoryRouteImport } from './routes/dashboard/wallet/history'
import { Route as DashboardWalletAutoRouteImport } from './routes/dashboard/wallet/auto'
import { Route as DashboardUtilitiesWaterRouteImport } from './routes/dashboard/utilities/water'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardWaterRoute = DashboardWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardWalletRouteRoute = DashboardWalletRouteRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUtilitiesRouteRoute = DashboardUtilitiesRouteRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRouteRoute = DashboardSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardWalletIndexRoute = DashboardWalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardWalletRouteRoute,
} as any)
const DashboardUtilitiesIndexRoute = DashboardUtilitiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardUtilitiesRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRouteRoute,
} as any)
const DashboardChatbotIndexRoute = DashboardChatbotIndexRouteImport.update({
  id: '/chatbot/',
  path: '/chatbot/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardWalletHistoryRoute = DashboardWalletHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardWalletRouteRoute,
} as any)
const DashboardWalletAutoRoute = DashboardWalletAutoRouteImport.update({
  id: '/auto',
  path: '/auto',
  getParentRoute: () => DashboardWalletRouteRoute,
} as any)
const DashboardUtilitiesWaterRoute = DashboardUtilitiesWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => DashboardUtilitiesRouteRoute,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/utilities': typeof DashboardUtilitiesRouteRouteWithChildren
  '/dashboard/wallet': typeof DashboardWalletRouteRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/dashboard/water': typeof DashboardWaterRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/utilities/water': typeof DashboardUtilitiesWaterRoute
  '/dashboard/wallet/auto': typeof DashboardWalletAutoRoute
  '/dashboard/wallet/history': typeof DashboardWalletHistoryRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/chatbot': typeof DashboardChatbotIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/utilities/': typeof DashboardUtilitiesIndexRoute
  '/dashboard/wallet/': typeof DashboardWalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/dashboard/water': typeof DashboardWaterRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/utilities/water': typeof DashboardUtilitiesWaterRoute
  '/dashboard/wallet/auto': typeof DashboardWalletAutoRoute
  '/dashboard/wallet/history': typeof DashboardWalletHistoryRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/chatbot': typeof DashboardChatbotIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/utilities': typeof DashboardUtilitiesIndexRoute
  '/dashboard/wallet': typeof DashboardWalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRouteRouteWithChildren
  '/dashboard/utilities': typeof DashboardUtilitiesRouteRouteWithChildren
  '/dashboard/wallet': typeof DashboardWalletRouteRouteWithChildren
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset': typeof AuthResetRoute
  '/dashboard/water': typeof DashboardWaterRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/utilities/water': typeof DashboardUtilitiesWaterRoute
  '/dashboard/wallet/auto': typeof DashboardWalletAutoRoute
  '/dashboard/wallet/history': typeof DashboardWalletHistoryRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/chatbot/': typeof DashboardChatbotIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/utilities/': typeof DashboardUtilitiesIndexRoute
  '/dashboard/wallet/': typeof DashboardWalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/utilities'
    | '/dashboard/wallet'
    | '/auth/register'
    | '/auth/reset'
    | '/dashboard/water'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/admin/users'
    | '/dashboard/utilities/water'
    | '/dashboard/wallet/auto'
    | '/dashboard/wallet/history'
    | '/dashboard/admin/'
    | '/dashboard/chatbot'
    | '/dashboard/settings/'
    | '/dashboard/utilities/'
    | '/dashboard/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/register'
    | '/auth/reset'
    | '/dashboard/water'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin/users'
    | '/dashboard/utilities/water'
    | '/dashboard/wallet/auto'
    | '/dashboard/wallet/history'
    | '/dashboard/admin'
    | '/dashboard/chatbot'
    | '/dashboard/settings'
    | '/dashboard/utilities'
    | '/dashboard/wallet'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/settings'
    | '/dashboard/utilities'
    | '/dashboard/wallet'
    | '/auth/register'
    | '/auth/reset'
    | '/dashboard/water'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/admin/users'
    | '/dashboard/utilities/water'
    | '/dashboard/wallet/auto'
    | '/dashboard/wallet/history'
    | '/dashboard/admin/'
    | '/dashboard/chatbot/'
    | '/dashboard/settings/'
    | '/dashboard/utilities/'
    | '/dashboard/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/water': {
      id: '/dashboard/water'
      path: '/water'
      fullPath: '/dashboard/water'
      preLoaderRoute: typeof DashboardWaterRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/utilities': {
      id: '/dashboard/utilities'
      path: '/utilities'
      fullPath: '/dashboard/utilities'
      preLoaderRoute: typeof DashboardUtilitiesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/wallet/': {
      id: '/dashboard/wallet/'
      path: '/'
      fullPath: '/dashboard/wallet/'
      preLoaderRoute: typeof DashboardWalletIndexRouteImport
      parentRoute: typeof DashboardWalletRouteRoute
    }
    '/dashboard/utilities/': {
      id: '/dashboard/utilities/'
      path: '/'
      fullPath: '/dashboard/utilities/'
      preLoaderRoute: typeof DashboardUtilitiesIndexRouteImport
      parentRoute: typeof DashboardUtilitiesRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRouteRoute
    }
    '/dashboard/chatbot/': {
      id: '/dashboard/chatbot/'
      path: '/chatbot'
      fullPath: '/dashboard/chatbot'
      preLoaderRoute: typeof DashboardChatbotIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/wallet/history': {
      id: '/dashboard/wallet/history'
      path: '/history'
      fullPath: '/dashboard/wallet/history'
      preLoaderRoute: typeof DashboardWalletHistoryRouteImport
      parentRoute: typeof DashboardWalletRouteRoute
    }
    '/dashboard/wallet/auto': {
      id: '/dashboard/wallet/auto'
      path: '/auto'
      fullPath: '/dashboard/wallet/auto'
      preLoaderRoute: typeof DashboardWalletAutoRouteImport
      parentRoute: typeof DashboardWalletRouteRoute
    }
    '/dashboard/utilities/water': {
      id: '/dashboard/utilities/water'
      path: '/water'
      fullPath: '/dashboard/utilities/water'
      preLoaderRoute: typeof DashboardUtilitiesWaterRouteImport
      parentRoute: typeof DashboardUtilitiesRouteRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetRoute: AuthResetRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardAdminRouteRouteChildren {
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardSettingsRouteRouteChildren {
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteRouteChildren: DashboardSettingsRouteRouteChildren =
  {
    DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  }

const DashboardSettingsRouteRouteWithChildren =
  DashboardSettingsRouteRoute._addFileChildren(
    DashboardSettingsRouteRouteChildren,
  )

interface DashboardUtilitiesRouteRouteChildren {
  DashboardUtilitiesWaterRoute: typeof DashboardUtilitiesWaterRoute
  DashboardUtilitiesIndexRoute: typeof DashboardUtilitiesIndexRoute
}

const DashboardUtilitiesRouteRouteChildren: DashboardUtilitiesRouteRouteChildren =
  {
    DashboardUtilitiesWaterRoute: DashboardUtilitiesWaterRoute,
    DashboardUtilitiesIndexRoute: DashboardUtilitiesIndexRoute,
  }

const DashboardUtilitiesRouteRouteWithChildren =
  DashboardUtilitiesRouteRoute._addFileChildren(
    DashboardUtilitiesRouteRouteChildren,
  )

interface DashboardWalletRouteRouteChildren {
  DashboardWalletAutoRoute: typeof DashboardWalletAutoRoute
  DashboardWalletHistoryRoute: typeof DashboardWalletHistoryRoute
  DashboardWalletIndexRoute: typeof DashboardWalletIndexRoute
}

const DashboardWalletRouteRouteChildren: DashboardWalletRouteRouteChildren = {
  DashboardWalletAutoRoute: DashboardWalletAutoRoute,
  DashboardWalletHistoryRoute: DashboardWalletHistoryRoute,
  DashboardWalletIndexRoute: DashboardWalletIndexRoute,
}

const DashboardWalletRouteRouteWithChildren =
  DashboardWalletRouteRoute._addFileChildren(DashboardWalletRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardSettingsRouteRoute: typeof DashboardSettingsRouteRouteWithChildren
  DashboardUtilitiesRouteRoute: typeof DashboardUtilitiesRouteRouteWithChildren
  DashboardWalletRouteRoute: typeof DashboardWalletRouteRouteWithChildren
  DashboardWaterRoute: typeof DashboardWaterRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardChatbotIndexRoute: typeof DashboardChatbotIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardSettingsRouteRoute: DashboardSettingsRouteRouteWithChildren,
  DashboardUtilitiesRouteRoute: DashboardUtilitiesRouteRouteWithChildren,
  DashboardWalletRouteRoute: DashboardWalletRouteRouteWithChildren,
  DashboardWaterRoute: DashboardWaterRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardChatbotIndexRoute: DashboardChatbotIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
